### ISSUE TITLE
连接报错了

### ISSUE THREAD

**Issue by weijunh** [baiyi11/flink-connector-jdbc-sqlserver#2]
is:issue is:open 连接 sqlserver报错java.lang.IllegalArgumentException: open() failed.The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:dc0523fc-2de8-4920-aeb2-0df85d596e5d,请问有人遇到过吗??怎么解决啊

**Comment by baiyi11** [comment]
你的sqlserver驱动版本是多少  
我用的是
   <dependency>
	<groupId>com.microsoft.sqlserver</groupId>
	<artifactId>mssql-jdbc</artifactId>
	<version>8.2.2.jre11</version>
  </dependency>

**Comment by weijunh** [comment]
> 
sqlserver 版本是2008 R2 (RTM) 
驱动刚刚试用了
com.microsoft.sqlserver
mssql-jdbc
8.2.2.jre8
报错 org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl [] - Interrupted while waiting for queue
但是yarn队列是正常的呀

**Comment by baiyi11** [comment]
网上说sqlserver 2008   驱动用 sqljdbc4

**Comment by weijunh** [comment]
> 
请问下楼主用的是哪个版本的sqlserver?

**Comment by weijunh** [comment]
> 你的sqlserver驱动版本是多少 我用的是 com.microsoft.sqlserver mssql-jdbc 8.2.2.jre11

flink1.12.7  是一样的实现方法吗?

**Comment by baiyi11** [comment]
> > 你的sqlserver驱动版本是多少 我用的是 com.microsoft.sqlserver mssql-jdbc 8.2.2.jre11
> 
> flink1.12.7 是一样的实现方法吗?

我用的是sqlserver 2012   ,驱动是com.microsoft.sql servermssql-jdbc  8.2.2.jre8，flink版本为1.13.0。以上两个connector 分别在 1.14 和1.13下打包成功。如果你用的是其他版本flink，需要自己打包。
